In [1]:
"""  
In this lab, the objective is to identify the customers who were active in both May and June, and how did their activity differ between months. 
To achieve this, follow these steps:

Establish a connection between Python and the Sakila database.

Write a Python function called rentals_month that retrieves rental data for a given month and year (passed as parameters) from the Sakila database as a Pandas DataFrame. 
The function should take in three parameters:

engine: an object representing the database connection engine to be used to establish a connection to the Sakila database.
month: an integer representing the month for which rental data is to be retrieved.
year: an integer representing the year for which rental data is to be retrieved.
The function should execute a SQL query to retrieve the rental data for the specified month and year from the rental table in the Sakila database, 
and return it as a pandas DataFrame.
Develop a Python function called rental_count_month that takes the DataFrame provided by rentals_month as 
input along with the month and year and returns a new DataFrame containing the number of rentals made by each customer_id during the selected month and year.

The function should also include the month and year as parameters and use them to name the new column according to the month and year, 
for example, if the input month is 05 and the year is 2005, the column name should be "rentals_05_2005".

Hint: Consider making use of pandas groupby()

Create a Python function called compare_rentals that takes two DataFrames as input containing the number of rentals made by each customer in different months and years.
 The function should return a combined DataFrame with a new 'difference' column, which is the difference between the number of rentals in the two months.
"""

'  \nIn this lab, the objective is to identify the customers who were active in both May and June, and how did their activity differ between months. \nTo achieve this, follow these steps:\n\nEstablish a connection between Python and the Sakila database.\n\nWrite a Python function called rentals_month that retrieves rental data for a given month and year (passed as parameters) from the Sakila database as a Pandas DataFrame. \nThe function should take in three parameters:\n\nengine: an object representing the database connection engine to be used to establish a connection to the Sakila database.\nmonth: an integer representing the month for which rental data is to be retrieved.\nyear: an integer representing the year for which rental data is to be retrieved.\nThe function should execute a SQL query to retrieve the rental data for the specified month and year from the rental table in the Sakila database, \nand return it as a pandas DataFrame.\nDevelop a Python function called rental_count_month that takes the DataFrame provided by rentals_month as \ninput along with the month and year and returns a new DataFrame containing the number of rentals made by each customer_id during the selected month and year.\n\nThe function should also include the month and year as parameters and use them to name the new column according to the month and year, \nfor example, if the input month is 05 and the year is 2005, the column name should be "rentals_05_2005".\n\nHint: Consider making use of pandas groupby()\n\nCreate a Python function called compare_rentals that takes two DataFrames as input containing the number of rentals made by each customer in different months and years.\n The function should return a combined DataFrame with a new \'difference\' column, which is the difference between the number of rentals in the two months.\n'

In [2]:
!pip install cryptography

Collecting cryptography
  Downloading cryptography-44.0.3-cp39-abi3-win_amd64.whl.metadata (5.7 kB)
Collecting cffi>=1.12 (from cryptography)
  Downloading cffi-1.17.1-cp312-cp312-win_amd64.whl.metadata (1.6 kB)
Collecting pycparser (from cffi>=1.12->cryptography)
  Using cached pycparser-2.22-py3-none-any.whl.metadata (943 bytes)
Downloading cryptography-44.0.3-cp39-abi3-win_amd64.whl (3.2 MB)
   ---------------------------------------- 0.0/3.2 MB ? eta -:--:--
   --------- ------------------------------ 0.8/3.2 MB 6.7 MB/s eta 0:00:01
   ----------------------------- ---------- 2.4/3.2 MB 6.1 MB/s eta 0:00:01
   ---------------------------------------  3.1/3.2 MB 5.4 MB/s eta 0:00:01
   ---------------------------------------  3.1/3.2 MB 5.4 MB/s eta 0:00:01
   ---------------------------------------  3.1/3.2 MB 5.4 MB/s eta 0:00:01
   ---------------------------------------  3.1/3.2 MB 5.4 MB/s eta 0:00:01
   ---------------------------------------- 3.2/3.2 MB 2.1 MB/s eta 0:00:00
Downloading cffi-1.17.1-cp312-cp312-win_amd64.whl (181 kB)
Using cached pycparser-2.22-py3-none-any.whl (117 kB)
Installing collected packages: pycparser, cffi, cryptography

   ---------------------------------------- 0/3 [pycparser]
   ---------------------------------------- 0/3 [pycparser]
   ---------------------------------------- 0/3 [pycparser]
   ---------------------------------------- 0/3 [pycparser]
   ---------------------------------------- 0/3 [pycparser]
   ------------- -------------------------- 1/3 [cffi]
   ------------- -------------------------- 1/3 [cffi]
   ------------- -------------------------- 1/3 [cffi]
   -------------------------- ------------- 2/3 [cryptography]
   -------------------------- ------------- 2/3 [cryptography]
   -------------------------- ------------- 2/3 [cryptography]
   -------------------------- ------------- 2/3 [cryptography]
   -------------------------- ------------- 2/3 [cryptography]
   -------------------------- ------------- 2/3 [cryptography]
   -------------------------- ------------- 2/3 [cryptography]
   -------------------------- ------------- 2/3 [cryptography]
   -------------------------- ------------- 2/3 [cryptography]
   -------------------------- ------------- 2/3 [cryptography]
   -------------------------- ------------- 2/3 [cryptography]
   -------------------------- ------------- 2/3 [cryptography]
   -------------------------- ------------- 2/3 [cryptography]
   ---------------------------------------- 3/3 [cryptography]

Successfully installed cffi-1.17.1 cryptography-44.0.3 pycparser-2.22

In [3]:
!pip install pymysql

Collecting pymysql
  Downloading PyMySQL-1.1.1-py3-none-any.whl.metadata (4.4 kB)
Downloading PyMySQL-1.1.1-py3-none-any.whl (44 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.1.1

In [4]:
!pip install sqlalchemy

Collecting sqlalchemy
  Downloading sqlalchemy-2.0.40-cp312-cp312-win_amd64.whl.metadata (9.9 kB)
Collecting greenlet>=1 (from sqlalchemy)
  Downloading greenlet-3.2.1-cp312-cp312-win_amd64.whl.metadata (4.2 kB)
Collecting typing-extensions>=4.6.0 (from sqlalchemy)
  Downloading typing_extensions-4.13.2-py3-none-any.whl.metadata (3.0 kB)
Downloading sqlalchemy-2.0.40-cp312-cp312-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ------------------- -------------------- 1.0/2.1 MB 7.2 MB/s eta 0:00:01
   ---------------------------------------  2.1/2.1 MB 5.6 MB/s eta 0:00:01
   ---------------------------------------  2.1/2.1 MB 5.6 MB/s eta 0:00:01
   ---------------------------------------  2.1/2.1 MB 5.6 MB/s eta 0:00:01
   ---------------------------------------  2.1/2.1 MB 5.6 MB/s eta 0:00:01
   ---------------------------------------  2.1/2.1 MB 5.6 MB/s eta 0:00:01
   ---------------------------------------- 2.1/2.1 MB 1.3 MB/s eta 0:00:00
Downloading greenlet-3.2.1-cp312-cp312-win_amd64.whl (296 kB)
Downloading typing_extensions-4.13.2-py3-none-any.whl (45 kB)
Installing collected packages: typing-extensions, greenlet, sqlalchemy

   ---------------------------------------- 0/3 [typing-extensions]
   ---------------------------------------- 0/3 [typing-extensions]
   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   ------------- -------------------------- 1/3 [greenlet]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   ---------------------------------------- 3/3 [sqlalchemy]

Successfully installed greenlet-3.2.1 sqlalchemy-2.0.40 typing-extensions-4.13.2

In [5]:
!pip install pandas

Collecting pandas
  Using cached pandas-2.2.3-cp312-cp312-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.26.0 (from pandas)
  Using cached numpy-2.2.5-cp312-cp312-win_amd64.whl.metadata (60 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\samya\pycharmprojects\lab-sql-python-connection\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Using cached pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Using cached tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\samya\pycharmprojects\lab-sql-python-connection\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-2.2.3-cp312-cp312-win_amd64.whl (11.5 MB)
Using cached numpy-2.2.5-cp312-cp312-win_amd64.whl (12.6 MB)
Using cached pytz-2025.2-py2.py3-none-any.whl (509 kB)
Using cached tzdata-2025.2-py2.py3-none-any.whl (347 kB)
Installing collected packages: pytz, tzdata, numpy, pandas

   ---------------------------------------- 0/4 [pytz]
   ---------------------------------------- 0/4 [pytz]
   ---------------------------------------- 0/4 [pytz]
   ---------------------------------------- 0/4 [pytz]
   ---------------------------------------- 0/4 [pytz]
   ---------------------------------------- 0/4 [pytz]
   ---------------------------------------- 0/4 [pytz]
   ---------------------------------------- 0/4 [pytz]
   ---------------------------------------- 0/4 [pytz]
   ---------------------------------------- 0/4 [pytz]
   ---------------------------------------- 0/4 [pytz]
   ---------------------------------------- 0/4 [pytz]
   ---------------------------------------- 0/4 [pytz]
   ---------------------------------------- 0/4 [pytz]
   ---------------------------------------- 0/4 [pytz]
   ---------- ----------------------------- 1/4 [tzdata]
   ---------- ----------------------------- 1/4 [tzdata]
   ---------- ----------------------------- 1/4 [tzdata]
   ---------- ----------------------------- 1/4 [tzdata]
   ---------- ----------------------------- 1/4 [tzdata]
   ---------- ----------------------------- 1/4 [tzdata]
   ---------- ----------------------------- 1/4 [tzdata]
   ---------- ----------------------------- 1/4 [tzdata]
   ---------- ----------------------------- 1/4 [tzdata]
   ---------- ----------------------------- 1/4 [tzdata]
   ---------- ----------------------------- 1/4 [tzdata]
   ---------- ----------------------------- 1/4 [tzdata]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   -------------------- ------------------- 2/4 [numpy]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]
   ------------------------------ --------- 3/4 [pandas]

In [6]:
!pip install numpy

Requirement already satisfied: numpy in c:\users\samya\pycharmprojects\lab-sql-python-connection\.venv\lib\site-packages (2.2.5)

In [7]:
import pandas as pd
import numpy as np
import pymysql
import getpass
from sqlalchemy import create_engine

In [8]:
password= getpass.getpass()

In [9]:
db = "sakila"
connection_string = 'mysql+pymysql://root:' + password + '@localhost/'+db
engine = create_engine(connection_string)
engine

Engine(mysql+pymysql://root:***@localhost/sakila)

In [29]:
from sqlalchemy import text



def rental_month(engine, month,year):
    with engine.connect() as connection:
        txt= f''' SELECT * FROM rental WHERE EXTRACT(MONTH FROM rental_date) = {month} AND EXTRACT(YEAR FROM rental_date) = {year}'''
        query = text(txt)
        result = connection.execute(query)
        return pd.DataFrame(result.all())

In [30]:
may_df=rental_month(engine, 5, 2005)
june_df = rental_month(engine, 6, 2005)

In [31]:
may_df

,rental_id,rental_date,inventory_id,customer_id,return_date,staff_id,last_update
0,1,2005-05-24 22:53:30,367,130,2005-05-26 22:04:30,1,2006-02-15 21:30:53
1,2,2005-05-24 22:54:33,1525,459,2005-05-28 19:40:33,1,2006-02-15 21:30:53
2,3,2005-05-24 23:03:39,1711,408,2005-06-01 22:12:39,1,2006-02-15 21:30:53
3,4,2005-05-24 23:04:41,2452,333,2005-06-03 01:43:41,2,2006-02-15 21:30:53
4,5,2005-05-24 23:05:21,2079,222,2005-06-02 04:33:21,1,2006-02-15 21:30:53
...,...,...,...,...,...,...,...
1151,1153,2005-05-31 21:36:44,2725,506,2005-06-10 01:26:44,2,2006-02-15 21:30:53
1152,1154,2005-05-31 21:42:09,2732,59,2005-06-08 16:40:09,1,2006-02-15 21:30:53
1153,1155,2005-05-31 22:17:11,2048,251,2005-06-04 20:27:11,2,2006-02-15 21:30:53
1154,1156,2005-05-31 22:37:34,460,106,2005-06-01 23:02:34,2,2006-02-15 21:30:53
1155,1157,2005-05-31 22:47:45,1449,61,2005-06-02 18:01:45,1,2006-02-15 21:30:53

In [32]:
june_df

,rental_id,rental_date,inventory_id,customer_id,return_date,staff_id,last_update
0,1158,2005-06-14 22:53:33,1632,416,2005-06-18 21:37:33,2,2006-02-15 21:30:53
1,1159,2005-06-14 22:55:13,4395,516,2005-06-17 02:11:13,1,2006-02-15 21:30:53
2,1160,2005-06-14 23:00:34,2795,239,2005-06-18 01:58:34,2,2006-02-15 21:30:53
3,1161,2005-06-14 23:07:08,1690,285,2005-06-21 17:12:08,1,2006-02-15 21:30:53
4,1162,2005-06-14 23:09:38,987,310,2005-06-23 22:00:38,1,2006-02-15 21:30:53
...,...,...,...,...,...,...,...
2306,3465,2005-06-21 22:10:01,1488,510,2005-06-30 21:35:01,1,2006-02-15 21:30:53
2307,3466,2005-06-21 22:13:33,371,226,2005-06-25 21:01:33,2,2006-02-15 21:30:53
2308,3467,2005-06-21 22:19:25,729,543,2005-06-27 00:03:25,2,2006-02-15 21:30:53
2309,3468,2005-06-21 22:43:45,2899,100,2005-06-30 01:49:45,1,2006-02-15 21:30:53
2310,3469,2005-06-21 22:48:59,4087,181,2005-06-28 19:32:59,1,2006-02-15 21:30:53

In [33]:
def rental_count_by_month():
    # Establishes a connection to the database using the provided SQLAlchemy engine
    with engine.connect() as connection:
        
        # SQL query: 
        # - Extracts the month from each rental_date as a 2-digit string ('%m')
        # - Counts the number of rentals per month
        # - Groups results by the extracted month
        # - Orders the result by month (chronologically)
        txt = '''
            SELECT DATE_FORMAT(rental_date, '%m') AS month, COUNT(*) AS rental_count
            FROM rental
            GROUP BY month
            ORDER BY month;
        '''
        
        # Prepares the SQL query for execution using SQLAlchemy's `text()` method
        query = text(txt)
        
        # Executes the query on the connected database
        result = connection.execute(query)
        
        # Converts the result to a pandas DataFrame with appropriate column names
        return pd.DataFrame(result.all(), columns=['month', 'rental_count'])

In [34]:
rental_count_by_month()

  month  rental_count
0    02           182
1    05          1156
2    06          2311
3    07          6709
4    08          5686

In [35]:
from sqlalchemy import text
import pandas as pd

def rental_count_month(month, year, engine):
    """
    Returns a DataFrame with number of rentals by customer for the given month and year.
    The column is dynamically named rentals_MM_YYYY.
    """
    month_str = f"{int(month):02d}"
    year_str = str(year)
    column_name = f"rentals_{month_str}_{year_str}"

    sql = f'''
        SELECT customer_id, COUNT(*) AS `{column_name}`
        FROM rental
        WHERE MONTH(rental_date) = :month AND YEAR(rental_date) = :year
        GROUP BY customer_id
        ORDER BY customer_id;
    '''

    with engine.connect() as connection:
        query = text(sql)
        result = connection.execute(query, {'month': int(month), 'year': int(year)})
        return pd.DataFrame(result.fetchall(), columns=['customer_id', column_name])

In [36]:
rental_count_month( 5, 2005,engine)

     customer_id  rentals_05_2005
0              1                2
1              2                1
2              3                2
3              5                3
4              6                3
..           ...              ...
515          594                4
516          595                1
517          596                6
518          597                2
519          599                1

[520 rows x 2 columns]

In [37]:
def compare_rental():
    sql= ''' 
         SELECT
            m1.customer_id,
            m1.rentals AS rentals_05_2005,
            m2.rentals AS rentals_06_2005,
            (m2.rentals - m1.rentals) AS difference
        FROM
            (
                SELECT customer_id, COUNT(*) AS rentals
                FROM rental
                WHERE MONTH(rental_date) = 5 AND YEAR(rental_date) = 2005
                GROUP BY customer_id
            ) m1
        JOIN
            (
                SELECT customer_id, COUNT(*) AS rentals
                FROM rental
                WHERE MONTH(rental_date) = 6 AND YEAR(rental_date) = 2005
                GROUP BY customer_id
            ) m2
        ON m1.customer_id = m2.customer_id;
         '''
         
    with engine.connect() as connection:
        query = text(sql)
        result = connection.execute(query)
        return pd.DataFrame(result.fetchall())

In [38]:
compare_rental()

     customer_id  rentals_05_2005  rentals_06_2005  difference
0              1                2                7           5
1              2                1                1           0
2              3                2                4           2
3              5                3                5           2
4              6                3                4           1
..           ...              ...              ...         ...
507          594                4                6           2
508          595                1                2           1
509          596                6                2          -4
510          597                2                3           1
511          599                1                4           3

[512 rows x 4 columns]